
services:
  web:
    image: docker.io/php:8.3-apache
    volumes:
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/entrypoint.sh:/entrypoint.sh
      - .:/var/www/
    entrypoint: /entrypoint.sh
###> doctrine/doctrine-bundle ###
  database:
    image: docker.io/mariadb:11.5
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: app
    volumes:
      - database_data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
